name: Build Android APK (robust)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Make gradlew executable if present
        run: |
          if [ -f ./gradlew ]; then chmod +x ./gradlew; fi

      - name: Ensure Gradle wrapper exists (generate if missing/corrupt)
        shell: bash
        run: |
          # If gradlew missing or obviously broken (tiny file), install system gradle and generate wrapper
          if [ ! -f ./gradlew ] || [ "$(stat -c%s ./gradlew)" -lt 100 ]; then
            echo "Gradle wrapper missing or invalid. Installing system gradle and generating wrapper..."
            sudo apt-get update -qq
            sudo apt-get install -y -qq gradle unzip
            echo "system gradle version:"
            gradle -v
            # generate wrapper with a modern Gradle version compatible with AGP 8.x
            gradle wrapper --gradle-version 8.5 --distribution-type all
          else
            echo "Gradle wrapper looks OK."
          fi
          chmod +x ./gradlew

      - name: Show quick repo & wrapper info (debug)
        run: |
          echo "=== repo top-level ==="
          ls -la
          echo ""
          echo "gradlew size:"
          stat -c "%n %s bytes" ./gradlew || true
          echo ""
          echo "gradle wrapper files:"
          ls -la gradle/wrapper || true

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Show Gradle version (wrapper)
        run: ./gradlew --version

      - name: Build debug APK
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Also attempt release/bundle (non-fatal)
        run: |
          ./gradlew assembleRelease --no-daemon --stacktrace || true
          ./gradlew bundleRelease --no-daemon --stacktrace || true

      - name: Find produced artifacts (debug)
        run: |
          echo "=== List .apk/.aab/.aar files found ==="
          find . -type f \( -iname "*.apk" -o -iname "*.aab" -o -iname "*.aar" \) -print -exec ls -l {} \; || true
          echo ""
          echo "=== List build/outputs directories ==="
          find . -type d -path "*/build/outputs/*" -print -exec ls -la {} \; || true

      - name: Upload any APK / AAB / AAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: |
            **/build/outputs/**/*.apk
            **/build/outputs/**/*.aab
            **/build/outputs/**/*.aar
            **/outputs/**/*.apk
            **/outputs/**/*.aab
            **/outputs/**/*.aar
