name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission to gradlew
      run: chmod +x gradlew
    
    # This step is added to trigger Gradle, which creates the .gradle directory
    - name: Sync Gradle and check dependencies
      run: ./gradlew dependencies
    
    # Now the caching step will find the .gradle directory and work correctly
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
    
    - name: Build debug APK
      run: ./gradlew assembleDebug
    
    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: app/build/outputs/apk/debug/app-debug.apk
