name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - uses: android-actions/setup-android@v2
    
    - run: |
        if [ ! -f "gradlew" ]; then
          gradle wrapper
        fi
        chmod +x gradlew
        ./gradlew assembleDebug
    
    - uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: app/build/outputs/apk/debug/app-debug.apk
